[package]
name = "ejemplos"
version = "0.1.0"
authors = ["Alumnos de clase de Graficación"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "guess"

